import React from "react";

const page = () => {
  return (
    <div>
      <h1 className="text-4xl text-center text-white mt-2">About Component</h1>
    </div>
  );
};

export default page;

export const metadata = {
  title: "About - Routing in NextJS",
  description: "Generated by create next app",
};
